### ISSUE TITLE
Not an issue, just want to say thank you

### ISSUE THREAD

**Issue by ivnnv** [k-yokoishi/zsh-prompt-generator#1]
You can close this issue as soon as you read it.

This is EXACTLY what I was looking for after upgrading to macOS Catalina and my old bash prompt didn't worked anymore and not wanting to learn yet another encoding thing to have a nice terminal.

Cheers!

**Comment by k-yokoishi** [comment]
Thank you for your comment!

As you said, Catalina's adoption of zsh as the standard shell was a major motivation for making this app. I wanted new users of zsh to easily customize their prompt.

So I'm really happy that this app reached to you :)

If you have any request, feel free to submit the issue again, happy zsh life 👍
