### ISSUE TITLE
Color and Formatting

### ISSUE THREAD

**Issue by r-mohammadi1** [k-yokoishi/zsh-prompt-generator#21]
An option to add colors and bold/underline would be nice.

**Comment by k-yokoishi** [comment]
Thank you for using!
Background color, font color and font weight(bold or normal) can be customized by clicking a tag in PROMPT field, please try it! But underline is not supported.
![zsh-prompt-generator](https://user-images.githubusercontent.com/18485918/124373164-d6316d00-dcca-11eb-8e64-55328dd9da4c.png)
